//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("DAHORModel", "FK_PRESUPUESTOS_SOLICITANTES", "SOLICITANTES", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(dahor.ad.ef.SOLICITANTES), "PRESUPUESTOS", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(dahor.ad.ef.PRESUPUESTOS))]

// Original file name:
// Generation date: 11/05/2013 11:55:33
namespace dahor.ad.ef
{
    
    /// <summary>
    /// There are no comments for DAHOREntities in the schema.
    /// </summary>
    public partial class DAHOREntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new DAHOREntities object using the connection string found in the 'DAHOREntities' section of the application configuration file.
        /// </summary>
        public DAHOREntities() : 
                base("name=DAHOREntities", "DAHOREntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new DAHOREntities object.
        /// </summary>
        public DAHOREntities(string connectionString) : 
                base(connectionString, "DAHOREntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new DAHOREntities object.
        /// </summary>
        public DAHOREntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "DAHOREntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for CANDIDATURAS in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<CANDIDATURAS> CANDIDATURAS
        {
            get
            {
                if ((this._CANDIDATURAS == null))
                {
                    this._CANDIDATURAS = base.CreateQuery<CANDIDATURAS>("[CANDIDATURAS]");
                }
                return this._CANDIDATURAS;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<CANDIDATURAS> _CANDIDATURAS;
        /// <summary>
        /// There are no comments for PRESUPUESTOS in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<PRESUPUESTOS> PRESUPUESTOS
        {
            get
            {
                if ((this._PRESUPUESTOS == null))
                {
                    this._PRESUPUESTOS = base.CreateQuery<PRESUPUESTOS>("[PRESUPUESTOS]");
                }
                return this._PRESUPUESTOS;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<PRESUPUESTOS> _PRESUPUESTOS;
        /// <summary>
        /// There are no comments for SOLICITANTES in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<SOLICITANTES> SOLICITANTES
        {
            get
            {
                if ((this._SOLICITANTES == null))
                {
                    this._SOLICITANTES = base.CreateQuery<SOLICITANTES>("[SOLICITANTES]");
                }
                return this._SOLICITANTES;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<SOLICITANTES> _SOLICITANTES;
        /// <summary>
        /// There are no comments for TIPOS_CENTRO in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<TIPOS_CENTRO> TIPOS_CENTRO
        {
            get
            {
                if ((this._TIPOS_CENTRO == null))
                {
                    this._TIPOS_CENTRO = base.CreateQuery<TIPOS_CENTRO>("[TIPOS_CENTRO]");
                }
                return this._TIPOS_CENTRO;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<TIPOS_CENTRO> _TIPOS_CENTRO;
        /// <summary>
        /// There are no comments for TIPOS_EMPLEO in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<TIPOS_EMPLEO> TIPOS_EMPLEO
        {
            get
            {
                if ((this._TIPOS_EMPLEO == null))
                {
                    this._TIPOS_EMPLEO = base.CreateQuery<TIPOS_EMPLEO>("[TIPOS_EMPLEO]");
                }
                return this._TIPOS_EMPLEO;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<TIPOS_EMPLEO> _TIPOS_EMPLEO;
        /// <summary>
        /// There are no comments for TIPOS_SERVICIO in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<TIPOS_SERVICIO> TIPOS_SERVICIO
        {
            get
            {
                if ((this._TIPOS_SERVICIO == null))
                {
                    this._TIPOS_SERVICIO = base.CreateQuery<TIPOS_SERVICIO>("[TIPOS_SERVICIO]");
                }
                return this._TIPOS_SERVICIO;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<TIPOS_SERVICIO> _TIPOS_SERVICIO;
        /// <summary>
        /// There are no comments for CANDIDATURAS in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToCANDIDATURAS(CANDIDATURAS cANDIDATURAS)
        {
            base.AddObject("CANDIDATURAS", cANDIDATURAS);
        }
        /// <summary>
        /// There are no comments for PRESUPUESTOS in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToPRESUPUESTOS(PRESUPUESTOS pRESUPUESTOS)
        {
            base.AddObject("PRESUPUESTOS", pRESUPUESTOS);
        }
        /// <summary>
        /// There are no comments for SOLICITANTES in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToSOLICITANTES(SOLICITANTES sOLICITANTES)
        {
            base.AddObject("SOLICITANTES", sOLICITANTES);
        }
        /// <summary>
        /// There are no comments for TIPOS_CENTRO in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToTIPOS_CENTRO(TIPOS_CENTRO tIPOS_CENTRO)
        {
            base.AddObject("TIPOS_CENTRO", tIPOS_CENTRO);
        }
        /// <summary>
        /// There are no comments for TIPOS_EMPLEO in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToTIPOS_EMPLEO(TIPOS_EMPLEO tIPOS_EMPLEO)
        {
            base.AddObject("TIPOS_EMPLEO", tIPOS_EMPLEO);
        }
        /// <summary>
        /// There are no comments for TIPOS_SERVICIO in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToTIPOS_SERVICIO(TIPOS_SERVICIO tIPOS_SERVICIO)
        {
            base.AddObject("TIPOS_SERVICIO", tIPOS_SERVICIO);
        }
    }
    /// <summary>
    /// There are no comments for DAHORModel.CANDIDATURAS in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="DAHORModel", Name="CANDIDATURAS")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class CANDIDATURAS : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new CANDIDATURAS object.
        /// </summary>
        /// <param name="id">Initial value of Id.</param>
        /// <param name="nombre">Initial value of Nombre.</param>
        /// <param name="fecha_Nacimiento">Initial value of Fecha_Nacimiento.</param>
        /// <param name="nacionalidad">Initial value of Nacionalidad.</param>
        /// <param name="telefono">Initial value of Telefono.</param>
        /// <param name="eMail">Initial value of EMail.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static CANDIDATURAS CreateCANDIDATURAS(long id, string nombre, global::System.DateTime fecha_Nacimiento, string nacionalidad, string telefono, string eMail)
        {
            CANDIDATURAS cANDIDATURAS = new CANDIDATURAS();
            cANDIDATURAS.Id = id;
            cANDIDATURAS.Nombre = nombre;
            cANDIDATURAS.Fecha_Nacimiento = fecha_Nacimiento;
            cANDIDATURAS.Nacionalidad = nacionalidad;
            cANDIDATURAS.Telefono = telefono;
            cANDIDATURAS.EMail = eMail;
            return cANDIDATURAS;
        }
        /// <summary>
        /// There are no comments for property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public long Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private long _Id;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIdChanging(long value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for property Nombre in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Nombre
        {
            get
            {
                return this._Nombre;
            }
            set
            {
                this.OnNombreChanging(value);
                this.ReportPropertyChanging("Nombre");
                this._Nombre = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Nombre");
                this.OnNombreChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Nombre;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNombreChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNombreChanged();
        /// <summary>
        /// There are no comments for property Apellidos in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Apellidos
        {
            get
            {
                return this._Apellidos;
            }
            set
            {
                this.OnApellidosChanging(value);
                this.ReportPropertyChanging("Apellidos");
                this._Apellidos = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Apellidos");
                this.OnApellidosChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Apellidos;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnApellidosChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnApellidosChanged();
        /// <summary>
        /// There are no comments for property Fecha_Nacimiento in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.DateTime Fecha_Nacimiento
        {
            get
            {
                return this._Fecha_Nacimiento;
            }
            set
            {
                this.OnFecha_NacimientoChanging(value);
                this.ReportPropertyChanging("Fecha_Nacimiento");
                this._Fecha_Nacimiento = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Fecha_Nacimiento");
                this.OnFecha_NacimientoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.DateTime _Fecha_Nacimiento;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnFecha_NacimientoChanging(global::System.DateTime value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnFecha_NacimientoChanged();
        /// <summary>
        /// There are no comments for property Nacionalidad in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Nacionalidad
        {
            get
            {
                return this._Nacionalidad;
            }
            set
            {
                this.OnNacionalidadChanging(value);
                this.ReportPropertyChanging("Nacionalidad");
                this._Nacionalidad = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Nacionalidad");
                this.OnNacionalidadChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Nacionalidad;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNacionalidadChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNacionalidadChanged();
        /// <summary>
        /// There are no comments for property Telefono in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Telefono
        {
            get
            {
                return this._Telefono;
            }
            set
            {
                this.OnTelefonoChanging(value);
                this.ReportPropertyChanging("Telefono");
                this._Telefono = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Telefono");
                this.OnTelefonoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Telefono;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnTelefonoChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnTelefonoChanged();
        /// <summary>
        /// There are no comments for property EMail in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string EMail
        {
            get
            {
                return this._EMail;
            }
            set
            {
                this.OnEMailChanging(value);
                this.ReportPropertyChanging("EMail");
                this._EMail = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("EMail");
                this.OnEMailChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _EMail;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnEMailChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnEMailChanged();
        /// <summary>
        /// There are no comments for property Puestos in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Puestos
        {
            get
            {
                return this._Puestos;
            }
            set
            {
                this.OnPuestosChanging(value);
                this.ReportPropertyChanging("Puestos");
                this._Puestos = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Puestos");
                this.OnPuestosChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Puestos;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnPuestosChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnPuestosChanged();
        /// <summary>
        /// There are no comments for property Experiencia in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Experiencia
        {
            get
            {
                return this._Experiencia;
            }
            set
            {
                this.OnExperienciaChanging(value);
                this.ReportPropertyChanging("Experiencia");
                this._Experiencia = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Experiencia");
                this.OnExperienciaChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Experiencia;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnExperienciaChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnExperienciaChanged();
        /// <summary>
        /// There are no comments for property Observaciones in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Observaciones
        {
            get
            {
                return this._Observaciones;
            }
            set
            {
                this.OnObservacionesChanging(value);
                this.ReportPropertyChanging("Observaciones");
                this._Observaciones = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Observaciones");
                this.OnObservacionesChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Observaciones;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnObservacionesChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnObservacionesChanged();
    }
    /// <summary>
    /// There are no comments for DAHORModel.PRESUPUESTOS in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Cod_Presupuesto
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="DAHORModel", Name="PRESUPUESTOS")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class PRESUPUESTOS : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new PRESUPUESTOS object.
        /// </summary>
        /// <param name="cod_Presupuesto">Initial value of Cod_Presupuesto.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static PRESUPUESTOS CreatePRESUPUESTOS(long cod_Presupuesto)
        {
            PRESUPUESTOS pRESUPUESTOS = new PRESUPUESTOS();
            pRESUPUESTOS.Cod_Presupuesto = cod_Presupuesto;
            return pRESUPUESTOS;
        }
        /// <summary>
        /// There are no comments for property Cod_Presupuesto in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public long Cod_Presupuesto
        {
            get
            {
                return this._Cod_Presupuesto;
            }
            set
            {
                this.OnCod_PresupuestoChanging(value);
                this.ReportPropertyChanging("Cod_Presupuesto");
                this._Cod_Presupuesto = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Cod_Presupuesto");
                this.OnCod_PresupuestoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private long _Cod_Presupuesto;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnCod_PresupuestoChanging(long value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnCod_PresupuestoChanged();
        /// <summary>
        /// There are no comments for property Empresa in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Empresa
        {
            get
            {
                return this._Empresa;
            }
            set
            {
                this.OnEmpresaChanging(value);
                this.ReportPropertyChanging("Empresa");
                this._Empresa = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Empresa");
                this.OnEmpresaChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Empresa;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnEmpresaChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnEmpresaChanged();
        /// <summary>
        /// There are no comments for property Tipos_Centro in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Tipos_Centro
        {
            get
            {
                return this._Tipos_Centro;
            }
            set
            {
                this.OnTipos_CentroChanging(value);
                this.ReportPropertyChanging("Tipos_Centro");
                this._Tipos_Centro = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Tipos_Centro");
                this.OnTipos_CentroChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Tipos_Centro;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnTipos_CentroChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnTipos_CentroChanged();
        /// <summary>
        /// There are no comments for property Tipos_Servicio in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Tipos_Servicio
        {
            get
            {
                return this._Tipos_Servicio;
            }
            set
            {
                this.OnTipos_ServicioChanging(value);
                this.ReportPropertyChanging("Tipos_Servicio");
                this._Tipos_Servicio = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Tipos_Servicio");
                this.OnTipos_ServicioChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Tipos_Servicio;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnTipos_ServicioChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnTipos_ServicioChanged();
        /// <summary>
        /// There are no comments for property Consulta in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Consulta
        {
            get
            {
                return this._Consulta;
            }
            set
            {
                this.OnConsultaChanging(value);
                this.ReportPropertyChanging("Consulta");
                this._Consulta = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Consulta");
                this.OnConsultaChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Consulta;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnConsultaChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnConsultaChanged();
        /// <summary>
        /// There are no comments for SOLICITANTES in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("DAHORModel", "FK_PRESUPUESTOS_SOLICITANTES", "SOLICITANTES")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public SOLICITANTES SOLICITANTES
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<SOLICITANTES>("DAHORModel.FK_PRESUPUESTOS_SOLICITANTES", "SOLICITANTES").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<SOLICITANTES>("DAHORModel.FK_PRESUPUESTOS_SOLICITANTES", "SOLICITANTES").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for SOLICITANTES in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<SOLICITANTES> SOLICITANTESReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<SOLICITANTES>("DAHORModel.FK_PRESUPUESTOS_SOLICITANTES", "SOLICITANTES");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<SOLICITANTES>("DAHORModel.FK_PRESUPUESTOS_SOLICITANTES", "SOLICITANTES", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for DAHORModel.SOLICITANTES in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Codigo
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="DAHORModel", Name="SOLICITANTES")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class SOLICITANTES : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new SOLICITANTES object.
        /// </summary>
        /// <param name="codigo">Initial value of Codigo.</param>
        /// <param name="nombre">Initial value of Nombre.</param>
        /// <param name="telefono">Initial value of Telefono.</param>
        /// <param name="mail">Initial value of Mail.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static SOLICITANTES CreateSOLICITANTES(long codigo, string nombre, string telefono, string mail)
        {
            SOLICITANTES sOLICITANTES = new SOLICITANTES();
            sOLICITANTES.Codigo = codigo;
            sOLICITANTES.Nombre = nombre;
            sOLICITANTES.Telefono = telefono;
            sOLICITANTES.Mail = mail;
            return sOLICITANTES;
        }
        /// <summary>
        /// There are no comments for property Codigo in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public long Codigo
        {
            get
            {
                return this._Codigo;
            }
            set
            {
                this.OnCodigoChanging(value);
                this.ReportPropertyChanging("Codigo");
                this._Codigo = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Codigo");
                this.OnCodigoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private long _Codigo;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnCodigoChanging(long value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnCodigoChanged();
        /// <summary>
        /// There are no comments for property Nombre in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Nombre
        {
            get
            {
                return this._Nombre;
            }
            set
            {
                this.OnNombreChanging(value);
                this.ReportPropertyChanging("Nombre");
                this._Nombre = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Nombre");
                this.OnNombreChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Nombre;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNombreChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNombreChanged();
        /// <summary>
        /// There are no comments for property Apellidos in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Apellidos
        {
            get
            {
                return this._Apellidos;
            }
            set
            {
                this.OnApellidosChanging(value);
                this.ReportPropertyChanging("Apellidos");
                this._Apellidos = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Apellidos");
                this.OnApellidosChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Apellidos;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnApellidosChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnApellidosChanged();
        /// <summary>
        /// There are no comments for property Direccion in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Direccion
        {
            get
            {
                return this._Direccion;
            }
            set
            {
                this.OnDireccionChanging(value);
                this.ReportPropertyChanging("Direccion");
                this._Direccion = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Direccion");
                this.OnDireccionChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Direccion;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnDireccionChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnDireccionChanged();
        /// <summary>
        /// There are no comments for property Poblacion in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Poblacion
        {
            get
            {
                return this._Poblacion;
            }
            set
            {
                this.OnPoblacionChanging(value);
                this.ReportPropertyChanging("Poblacion");
                this._Poblacion = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Poblacion");
                this.OnPoblacionChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Poblacion;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnPoblacionChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnPoblacionChanged();
        /// <summary>
        /// There are no comments for property CP in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string CP
        {
            get
            {
                return this._CP;
            }
            set
            {
                this.OnCPChanging(value);
                this.ReportPropertyChanging("CP");
                this._CP = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("CP");
                this.OnCPChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _CP;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnCPChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnCPChanged();
        /// <summary>
        /// There are no comments for property Telefono in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Telefono
        {
            get
            {
                return this._Telefono;
            }
            set
            {
                this.OnTelefonoChanging(value);
                this.ReportPropertyChanging("Telefono");
                this._Telefono = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Telefono");
                this.OnTelefonoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Telefono;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnTelefonoChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnTelefonoChanged();
        /// <summary>
        /// There are no comments for property Mail in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Mail
        {
            get
            {
                return this._Mail;
            }
            set
            {
                this.OnMailChanging(value);
                this.ReportPropertyChanging("Mail");
                this._Mail = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Mail");
                this.OnMailChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Mail;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnMailChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnMailChanged();
        /// <summary>
        /// There are no comments for property Horario in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Horario
        {
            get
            {
                return this._Horario;
            }
            set
            {
                this.OnHorarioChanging(value);
                this.ReportPropertyChanging("Horario");
                this._Horario = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Horario");
                this.OnHorarioChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Horario;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnHorarioChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnHorarioChanged();
        /// <summary>
        /// There are no comments for PRESUPUESTOS in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("DAHORModel", "FK_PRESUPUESTOS_SOLICITANTES", "PRESUPUESTOS")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<PRESUPUESTOS> PRESUPUESTOS
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<PRESUPUESTOS>("DAHORModel.FK_PRESUPUESTOS_SOLICITANTES", "PRESUPUESTOS");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<PRESUPUESTOS>("DAHORModel.FK_PRESUPUESTOS_SOLICITANTES", "PRESUPUESTOS", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for DAHORModel.TIPOS_CENTRO in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Codigo
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="DAHORModel", Name="TIPOS_CENTRO")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class TIPOS_CENTRO : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new TIPOS_CENTRO object.
        /// </summary>
        /// <param name="codigo">Initial value of Codigo.</param>
        /// <param name="nombre">Initial value of Nombre.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static TIPOS_CENTRO CreateTIPOS_CENTRO(short codigo, string nombre)
        {
            TIPOS_CENTRO tIPOS_CENTRO = new TIPOS_CENTRO();
            tIPOS_CENTRO.Codigo = codigo;
            tIPOS_CENTRO.Nombre = nombre;
            return tIPOS_CENTRO;
        }
        /// <summary>
        /// There are no comments for property Codigo in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public short Codigo
        {
            get
            {
                return this._Codigo;
            }
            set
            {
                this.OnCodigoChanging(value);
                this.ReportPropertyChanging("Codigo");
                this._Codigo = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Codigo");
                this.OnCodigoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private short _Codigo;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnCodigoChanging(short value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnCodigoChanged();
        /// <summary>
        /// There are no comments for property Nombre in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Nombre
        {
            get
            {
                return this._Nombre;
            }
            set
            {
                this.OnNombreChanging(value);
                this.ReportPropertyChanging("Nombre");
                this._Nombre = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Nombre");
                this.OnNombreChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Nombre;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNombreChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNombreChanged();
    }
    /// <summary>
    /// There are no comments for DAHORModel.TIPOS_EMPLEO in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Codigo
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="DAHORModel", Name="TIPOS_EMPLEO")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class TIPOS_EMPLEO : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new TIPOS_EMPLEO object.
        /// </summary>
        /// <param name="codigo">Initial value of Codigo.</param>
        /// <param name="tipo">Initial value of Tipo.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static TIPOS_EMPLEO CreateTIPOS_EMPLEO(short codigo, string tipo)
        {
            TIPOS_EMPLEO tIPOS_EMPLEO = new TIPOS_EMPLEO();
            tIPOS_EMPLEO.Codigo = codigo;
            tIPOS_EMPLEO.Tipo = tipo;
            return tIPOS_EMPLEO;
        }
        /// <summary>
        /// There are no comments for property Codigo in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public short Codigo
        {
            get
            {
                return this._Codigo;
            }
            set
            {
                this.OnCodigoChanging(value);
                this.ReportPropertyChanging("Codigo");
                this._Codigo = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Codigo");
                this.OnCodigoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private short _Codigo;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnCodigoChanging(short value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnCodigoChanged();
        /// <summary>
        /// There are no comments for property Tipo in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Tipo
        {
            get
            {
                return this._Tipo;
            }
            set
            {
                this.OnTipoChanging(value);
                this.ReportPropertyChanging("Tipo");
                this._Tipo = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Tipo");
                this.OnTipoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Tipo;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnTipoChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnTipoChanged();
    }
    /// <summary>
    /// There are no comments for DAHORModel.TIPOS_SERVICIO in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Codigo
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="DAHORModel", Name="TIPOS_SERVICIO")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class TIPOS_SERVICIO : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new TIPOS_SERVICIO object.
        /// </summary>
        /// <param name="codigo">Initial value of Codigo.</param>
        /// <param name="nombre">Initial value of Nombre.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static TIPOS_SERVICIO CreateTIPOS_SERVICIO(short codigo, string nombre)
        {
            TIPOS_SERVICIO tIPOS_SERVICIO = new TIPOS_SERVICIO();
            tIPOS_SERVICIO.Codigo = codigo;
            tIPOS_SERVICIO.Nombre = nombre;
            return tIPOS_SERVICIO;
        }
        /// <summary>
        /// There are no comments for property Codigo in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public short Codigo
        {
            get
            {
                return this._Codigo;
            }
            set
            {
                this.OnCodigoChanging(value);
                this.ReportPropertyChanging("Codigo");
                this._Codigo = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Codigo");
                this.OnCodigoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private short _Codigo;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnCodigoChanging(short value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnCodigoChanged();
        /// <summary>
        /// There are no comments for property Nombre in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Nombre
        {
            get
            {
                return this._Nombre;
            }
            set
            {
                this.OnNombreChanging(value);
                this.ReportPropertyChanging("Nombre");
                this._Nombre = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Nombre");
                this.OnNombreChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Nombre;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNombreChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNombreChanged();
    }
}
