//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dahor.iu.mail.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Classes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Classes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("dahor.iu.mail.Resources.Classes", typeof(Classes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to width:900px; margin:0px;.
        /// </summary>
        internal static string body_table {
            get {
                return ResourceManager.GetString("body_table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to border-style:solid; border-width:1px;.
        /// </summary>
        internal static string body_table_tr_td {
            get {
                return ResourceManager.GetString("body_table_tr_td", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to margin:0px 0px 0px 10px; padding:0px; font:bold 90%/180% \&quot;Trebuchet MS\&quot;, \&quot;Lucida Grande\&quot;, \&quot;Bitstream Vera Sans\&quot;, Arial, Helvetica, sans-serif; color:#000000; border-style:solid; border-width:1px;.
        /// </summary>
        internal static string body_table_tr_td_label {
            get {
                return ResourceManager.GetString("body_table_tr_td_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to width:170px; border-style:solid; border-width:1px;vertical-align:top;.
        /// </summary>
        internal static string body_table_tr_td_tipoinfo {
            get {
                return ResourceManager.GetString("body_table_tr_td_tipoinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vertical-align:top; width:170px; border-style:solid; border-width:1px;.
        /// </summary>
        internal static string body_table_tr_td_top {
            get {
                return ResourceManager.GetString("body_table_tr_td_top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to margin:0px 0px 0px 15px;.
        /// </summary>
        internal static string body_ul {
            get {
                return ResourceManager.GetString("body_ul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to font: normal 28px Georgia,Trebuchet MS,Arial, Helvetica, sans-serif; color:#000066; margin: 0px 0px 0px 0px; padding: 0px 0px 0px 0px;.
        /// </summary>
        internal static string p_titulo {
            get {
                return ResourceManager.GetString("p_titulo", resourceCulture);
            }
        }
    }
}
