//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dahor.iu.mail.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MailInfo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MailInfo() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("dahor.iu.mail.Resources.MailInfo", typeof(MailInfo).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MailFrom.
        /// </summary>
        internal static string AppSettingMailFrom {
            get {
                return ResourceManager.GetString("AppSettingMailFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MailTo.
        /// </summary>
        internal static string AppSettingMailTo {
            get {
                return ResourceManager.GetString("AppSettingMailTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FormatoMailCand.
        /// </summary>
        internal static string AppSettingTipoMailCand {
            get {
                return ResourceManager.GetString("AppSettingTipoMailCand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FormatoMailPresup.
        /// </summary>
        internal static string AppSettingTipoMailPresup {
            get {
                return ResourceManager.GetString("AppSettingTipoMailPresup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd/MM/yyyy.
        /// </summary>
        internal static string date_format {
            get {
                return ResourceManager.GetString("date_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to html.
        /// </summary>
        internal static string FormatoHTML {
            get {
                return ResourceManager.GetString("FormatoHTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to txt.
        /// </summary>
        internal static string FormatoTXT {
            get {
                return ResourceManager.GetString("FormatoTXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOLICITUD DE TRABAJO DESDE WEB DAHOR.
        /// </summary>
        internal static string SubjectCandidatura {
            get {
                return ResourceManager.GetString("SubjectCandidatura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOLICITUD DE PRESUPUESTO DESDE WEB DAHOR.
        /// </summary>
        internal static string SubjectPresupuesto {
            get {
                return ResourceManager.GetString("SubjectPresupuesto", resourceCulture);
            }
        }
    }
}
