//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Generics {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Generics() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Generics", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd/MM/yyyy.
        /// </summary>
        internal static string date_format {
            get {
                return ResourceManager.GetString("date_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to configurarTextoExperiencia.
        /// </summary>
        internal static string func_configTextoExperiencia {
            get {
                return ResourceManager.GetString("func_configTextoExperiencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~\\Principal.aspx?info=jobs&amp;aptdo=solicok.
        /// </summary>
        internal static string pagejobs {
            get {
                return ResourceManager.GetString("pagejobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~\\Principal.aspx?info=presup&amp;aptdo=mailok.
        /// </summary>
        internal static string pagepresup {
            get {
                return ResourceManager.GetString("pagepresup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aptdo.
        /// </summary>
        internal static string param_aptdo {
            get {
                return ResourceManager.GetString("param_aptdo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to info.
        /// </summary>
        internal static string param_info {
            get {
                return ResourceManager.GetString("param_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Error/ErrorGenerico.html.
        /// </summary>
        internal static string url_error {
            get {
                return ResourceManager.GetString("url_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btnEnvioMail.
        /// </summary>
        internal static string vbe_btnEnvioMail {
            get {
                return ResourceManager.GetString("vbe_btnEnvioMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ddlHorario.
        /// </summary>
        internal static string vbe_ddlHorario {
            get {
                return ResourceManager.GetString("vbe_ddlHorario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tbHoraDesde.
        /// </summary>
        internal static string vbe_nomHoraDesde {
            get {
                return ResourceManager.GetString("vbe_nomHoraDesde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tbHoraHasta.
        /// </summary>
        internal static string vbe_nomHoraHasta {
            get {
                return ResourceManager.GetString("vbe_nomHoraHasta", resourceCulture);
            }
        }
    }
}
